export const products = [
    {
        "id": "mw-0",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #1",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-0.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 150
    },
    {
        "id": "mw-1",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #2",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-1.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 200
    },
    {
        "id": "mw-2",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #3",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-2.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 250
    },
    {
        "id": "mw-3",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #4",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-3.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 300
    },
    {
        "id": "mw-4",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #5",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-4.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 350
    },
    {
        "id": "mw-5",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #6",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-5.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad.",
        "sales": 400
    },
    {
        "id": "mw-6",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #7",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-6.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-7",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #8",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-7.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-8",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #9",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-8.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-9",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #10",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-9.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-10",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #11",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-10.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-11",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #12",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-11.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-12",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #13",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-12.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-13",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #14",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-13.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-14",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #15",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-14.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-15",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #16",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-15.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-16",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #17",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-16.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-17",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #18",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-17.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-18",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #19",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-18.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-19",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #20",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-19.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-20",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #21",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-20.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-21",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #22",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-21.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-22",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #23",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-22.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-23",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #24",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-23.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-24",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #25",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-24.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-25",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #26",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-25.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-26",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #27",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-26.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-27",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #28",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-27.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-28",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #29",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-28.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-29",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #30",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-29.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-30",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #31",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-30.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-31",
        "itemSubCategory": "Tazas",
        "name": "Magic World Exclusive Piece #32",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-31.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-32",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #33",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-32.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-33",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #34",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-33.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-34",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #35",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-34.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-35",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #36",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-35.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-36",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #37",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-36.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-37",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #38",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-37.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-38",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #39",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-38.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-39",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #40",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-39.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-40",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #41",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-40.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-41",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #42",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-41.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-42",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #43",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-42.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-43",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #44",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-43.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-44",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #45",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-44.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-45",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #46",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-45.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-46",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #47",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-46.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-47",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #48",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-47.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-48",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #49",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-48.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-49",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #50",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-49.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-50",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #51",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-50.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-51",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #52",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-51.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-52",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #53",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-52.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-53",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #54",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-53.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-54",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #55",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-54.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-55",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #56",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-55.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-56",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #57",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-56.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-57",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #58",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-57.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-58",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #59",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-58.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-59",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #60",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-59.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-60",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #61",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-60.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-61",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #62",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-61.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-62",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #63",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-62.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-63",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #64",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-63.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-64",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #65",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-64.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-65",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #66",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-65.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-66",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #67",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-66.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-67",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #68",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-67.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-68",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #69",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-68.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-69",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #70",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-69.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-70",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #71",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-70.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-71",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #72",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-71.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-72",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #73",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-72.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-73",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #74",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-73.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-74",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #75",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-74.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-75",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #76",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-75.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-76",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #77",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-76.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-77",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #78",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-77.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-78",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #79",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-78.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-79",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #80",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-79.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-80",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #81",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-80.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-81",
        "itemSubCategory": "Vasos y Termos",
        "name": "Magic World Exclusive Piece #82",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-81.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-82",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #83",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-82.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-83",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #84",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-83.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-84",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #85",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-84.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-85",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #86",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-85.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-86",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #87",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-86.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-87",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #88",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-87.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-88",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #89",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-88.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-89",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #90",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-89.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-90",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #91",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-90.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-91",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #92",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-91.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-92",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #93",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-92.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-93",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #94",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-93.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-94",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #95",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-94.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-95",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #96",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-95.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-96",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #97",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-96.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-97",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #98",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-97.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-98",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #99",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-98.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-99",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #100",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-99.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-100",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #101",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-100.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-101",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #102",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-101.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-102",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #103",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-102.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-103",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #104",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-103.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-104",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #105",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-104.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-105",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #106",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-105.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-106",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #107",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-106.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-107",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #108",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-107.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-108",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #109",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-108.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-109",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #110",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-109.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-110",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #111",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-110.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-111",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #112",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-111.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-112",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #113",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-112.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-113",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #114",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-113.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-114",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #115",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-114.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-115",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #116",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-115.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-116",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #117",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-116.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-117",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #118",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-117.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-118",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #119",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-118.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-119",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #120",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-119.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-120",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #121",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-120.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-121",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #122",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-121.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-122",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #123",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-122.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-123",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #124",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-123.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-124",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #125",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-124.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-125",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #126",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-125.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-126",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #127",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-126.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-127",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #128",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-127.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-128",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #129",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-128.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-129",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #130",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-129.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-130",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #131",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-130.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-131",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #132",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-131.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-132",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #133",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-132.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-133",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #134",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-133.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-134",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #135",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-134.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-135",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #136",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-135.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-136",
        "itemSubCategory": "Loncheras",
        "name": "Magic World Exclusive Piece #137",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-136.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-137",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #138",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-137.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-138",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #139",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-138.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-139",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #140",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-139.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-140",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #141",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-140.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-141",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #142",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-141.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-142",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #143",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-142.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-143",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #144",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-143.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-144",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #145",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-144.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-145",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #146",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-145.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-146",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #147",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-146.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-147",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #148",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-147.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-148",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #149",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-148.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-149",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #150",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-149.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-150",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #151",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-150.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-151",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #152",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-151.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-152",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #153",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-152.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-153",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #154",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-153.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-154",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #155",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-154.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-155",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #156",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-155.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-156",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #157",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-156.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-157",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #158",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-157.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-158",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #159",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-158.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-159",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #160",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-159.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-160",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #161",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-160.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-161",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #162",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-161.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-162",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #163",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-162.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-163",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #164",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-163.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-164",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #165",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-164.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-165",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #166",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-165.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-166",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #167",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-166.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },
    {
        "id": "mw-167",
        "itemSubCategory": "Accesorios",
        "name": "Magic World Exclusive Piece #168",
        "price": 450.0,
        "brand": "Magic World",
        "type": "Trends",
        "category": "Magic World",
        "image": "mw-167.jpg",
        "description": "Producto auténtico de la colección Magic World. Elaborado con materiales de alta calidad."
    },

];

if (typeof window !== 'undefined') {
    window.products = products;
}
